// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#ifndef CONCEPTRODON_MOULDIVORE_RECUR_H
#define CONCEPTRODON_MOULDIVORE_RECUR_H

#include <type_traits>

namespace Conceptrodon {
namespace Mouldivore {

template<template<typename...> class History>
struct Recur
{
    template<template<typename...> class...LessonsLearned>
    struct ProtoRoad
    {
        template<typename...Sacrifices>
        static consteval auto idyl()
        {



/*1*/
/******************************************************************************************************/
            if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                        Sacrifices...
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                        Sacrifices...
                >>{};
            }
/******************************************************************************************************/




/*2*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                        Sacrifices...
                    >
                >>{};
            }
/******************************************************************************************************/




/*3*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*4*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*5*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*6*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*7*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*8*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*9*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*10*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*11*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*12*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*13*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*14*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*15*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*16*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*17*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*18*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*19*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*20*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*21*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*22*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*23*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*24*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*25*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*26*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*27*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*28*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*29*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*30*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*31*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/*32*/
/******************************************************************************************************/
            else if constexpr 
            (
                (...&&LessonsLearned<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >::value)
            )
            {
                return std::type_identity<History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >>{};
            }
/******************************************************************************************************/




/******************************************************************************************************/
            else 
            {
                return idyl<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                    History<
                        Sacrifices...
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                    >
                >();
            }
/******************************************************************************************************/




        }

        template<typename...Sacrifices>
        using Mold = decltype(idyl<Sacrifices...>())::type;
    };

    template<template<typename...> class...Agreements>
    using Road = ProtoRoad<Agreements...>;
};

}}

#endif