// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

/******************************************************************************************************/
#ifdef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#error "CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY has already been defined"
#endif

#ifdef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#error "CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE has already been defined"
#endif

#ifdef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#error "CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE has already been defined"
#endif

#ifdef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
#error "CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE has already been defined"
#endif
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_ROAD_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_ROAD_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_ROAD_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_ROAD_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/





/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_RAIL_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_RAIL_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_RAIL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_RAIL_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_FLOW_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_FLOW_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_FLOW_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_FLOW_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_SAIL_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_SAIL_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_SAIL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_SAIL_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_SNOW_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_SNOW_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_SNOW_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_SNOW_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_HAIL_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_HAIL_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_HAIL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_HAIL_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_LULL_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_LULL_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_LULL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_LULL_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_CALM_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_CALM_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_CALM_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_CALM_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_GRIT_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_GRIT_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_GRIT_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_GRIT_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_WILL_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_WILL_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_WILL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_WILL_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_GLOW_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_GLOW_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_GLOW_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_GLOW_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_DAWN_PARAMETER_CATEGORY
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_DAWN_PROTO_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_DAWN_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_DAWN_UNI_TEMPLATE

#include "conceptrodon/descend/microbiota/raileus/classic_trek/ascend/classic_trek.hpp"

#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_RAILEUS_CLASSIC_TREK_COMPOSITION_UNI_TEMPLATE
/******************************************************************************************************/
