// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#include "conceptrodon/omennivore/concepts/descend/descend/unconformed.hpp"
#include "conceptrodon/omennivore/concepts/descend/conformed.hpp"
#include "conceptrodon/omennivore/concepts/descend/not_almanac.hpp"
#include "conceptrodon/omennivore/concepts/descend/not_freeway.hpp"
#include "conceptrodon/omennivore/concepts/descend/not_pottery.hpp"
#include "conceptrodon/omennivore/concepts/descend/not_railway.hpp"
#include "conceptrodon/omennivore/concepts/descend/unvaluable.hpp"
#include "conceptrodon/omennivore/concepts/almanac_probe.hpp"
#include "conceptrodon/omennivore/concepts/flow_probe.hpp"
#include "conceptrodon/omennivore/concepts/freeway_probe.hpp"
#include "conceptrodon/omennivore/concepts/mold_probe.hpp"
#include "conceptrodon/omennivore/concepts/page_probe.hpp"
#include "conceptrodon/omennivore/concepts/pottery_probe.hpp"
#include "conceptrodon/omennivore/concepts/rail_probe.hpp"
#include "conceptrodon/omennivore/concepts/railway_probe.hpp"
#include "conceptrodon/omennivore/concepts/road_probe.hpp"
#include "conceptrodon/omennivore/concepts/sail_probe.hpp"
#include "conceptrodon/omennivore/concepts/typical.hpp"
#include "conceptrodon/omennivore/concepts/untypical.hpp"
#include "conceptrodon/omennivore/concepts/valuable.hpp"
#include "conceptrodon/omennivore/among.hpp"
#include "conceptrodon/omennivore/extend_back.hpp"
#include "conceptrodon/omennivore/extend_front.hpp"
#include "conceptrodon/omennivore/flatten.hpp"
#include "conceptrodon/omennivore/is_almanac.hpp"
#include "conceptrodon/omennivore/is_freeway.hpp"
#include "conceptrodon/omennivore/is_pottery.hpp"
#include "conceptrodon/omennivore/is_railway.hpp"
#include "conceptrodon/omennivore/send.hpp"
#include "conceptrodon/omennivore/total.hpp"


#include "conceptrodon/descend/omennivore/concepts/descend/nonzero_peg.hpp"
#include "conceptrodon/descend/omennivore/concepts/descend/zero_peg.hpp"
#include "conceptrodon/descend/omennivore/concepts/nonzero_value.hpp"
#include "conceptrodon/descend/omennivore/concepts/not_peg.hpp"
#include "conceptrodon/descend/omennivore/concepts/peg_probe.hpp"
#include "conceptrodon/descend/omennivore/concepts/zero_value.hpp"
#include "conceptrodon/descend/omennivore/alter_types.hpp"
#include "conceptrodon/descend/omennivore/breeze.hpp"
#include "conceptrodon/descend/omennivore/harvest_types.hpp"
#include "conceptrodon/descend/omennivore/harvest_variables.hpp"
#include "conceptrodon/descend/omennivore/insert_types.hpp"
#include "conceptrodon/descend/omennivore/insert_variables.hpp"
#include "conceptrodon/descend/omennivore/modify_types.hpp"
#include "conceptrodon/descend/omennivore/modify_variables.hpp"
#include "conceptrodon/descend/omennivore/paste.hpp"
#include "conceptrodon/descend/omennivore/remove_types.hpp"
#include "conceptrodon/descend/omennivore/remove_variables.hpp"
#include "conceptrodon/descend/omennivore/repack.hpp"
#include "conceptrodon/descend/omennivore/zip.hpp"

#include "conceptrodon/descend/descend/omennivore/wind.hpp"