// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#include "conceptrodon/pagelivore/agent.hpp"
#include "conceptrodon/pagelivore/among.hpp"
#include "conceptrodon/pagelivore/bind_back.hpp"
#include "conceptrodon/pagelivore/bind_front.hpp"
#include "conceptrodon/pagelivore/conjunction.hpp"
#include "conceptrodon/pagelivore/disjunction.hpp"
#include "conceptrodon/pagelivore/find.hpp"
#include "conceptrodon/pagelivore/fold_left_first.hpp"
#include "conceptrodon/pagelivore/fold_left.hpp"
#include "conceptrodon/pagelivore/fold_right_last.hpp"
#include "conceptrodon/pagelivore/fold_right.hpp"
#include "conceptrodon/pagelivore/independent_find.hpp"
#include "conceptrodon/pagelivore/independent_left_interview.hpp"
#include "conceptrodon/pagelivore/independent_right_interview.hpp"
#include "conceptrodon/pagelivore/is_specialization.hpp"
#include "conceptrodon/pagelivore/left_interview.hpp"
#include "conceptrodon/pagelivore/look_for.hpp"
#include "conceptrodon/pagelivore/negation.hpp"
#include "conceptrodon/pagelivore/repack.hpp"
#include "conceptrodon/pagelivore/right_interview.hpp"
#include "conceptrodon/pagelivore/situational.hpp"
#include "conceptrodon/pagelivore/terse_find.hpp"
#include "conceptrodon/pagelivore/terse_left_interview.hpp"
#include "conceptrodon/pagelivore/terse_right_interview.hpp"
#include "conceptrodon/pagelivore/trip.hpp"

#include "conceptrodon/descend/pagelivore/dismiss.hpp"
#include "conceptrodon/descend/pagelivore/erase.hpp"
#include "conceptrodon/descend/pagelivore/front.hpp"
#include "conceptrodon/descend/pagelivore/gauge.hpp"
#include "conceptrodon/descend/pagelivore/grade.hpp"
#include "conceptrodon/descend/pagelivore/harvest.hpp"
#include "conceptrodon/descend/pagelivore/inject.hpp"
#include "conceptrodon/descend/pagelivore/left_review.hpp"
#include "conceptrodon/descend/pagelivore/observe.hpp"
#include "conceptrodon/descend/pagelivore/plume.hpp"
#include "conceptrodon/descend/pagelivore/preen.hpp"
#include "conceptrodon/descend/pagelivore/refurbish.hpp"
#include "conceptrodon/descend/pagelivore/renovate.hpp"
#include "conceptrodon/descend/pagelivore/repeat.hpp"
#include "conceptrodon/descend/pagelivore/reverse.hpp"
#include "conceptrodon/descend/pagelivore/right_review.hpp"
#include "conceptrodon/descend/pagelivore/rise.hpp"
#include "conceptrodon/descend/pagelivore/rotate.hpp"
#include "conceptrodon/descend/pagelivore/segment.hpp"
#include "conceptrodon/descend/pagelivore/sieve.hpp"
#include "conceptrodon/descend/pagelivore/slice.hpp"
#include "conceptrodon/descend/pagelivore/tale.hpp"
#include "conceptrodon/descend/pagelivore/transform.hpp"
#include "conceptrodon/descend/pagelivore/travel.hpp"
#include "conceptrodon/descend/pagelivore/trim.hpp"


#include "conceptrodon/descend/descend/pagelivore/bind.hpp"
#include "conceptrodon/descend/descend/pagelivore/filter.hpp"
#include "conceptrodon/descend/descend/pagelivore/insert.hpp"
#include "conceptrodon/descend/descend/pagelivore/modify.hpp"
#include "conceptrodon/descend/descend/pagelivore/remove.hpp"