// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#include "conceptrodon/typelivore/concepts/clarify.hpp"
#include "conceptrodon/typelivore/concepts/falsify.hpp"
#include "conceptrodon/typelivore/among.hpp"
#include "conceptrodon/typelivore/conditional.hpp"
#include "conceptrodon/typelivore/contains.hpp"
#include "conceptrodon/typelivore/find.hpp"
#include "conceptrodon/typelivore/fold_left_first.hpp"
#include "conceptrodon/typelivore/fold_left.hpp"
#include "conceptrodon/typelivore/is_different.hpp"
#include "conceptrodon/typelivore/is_same.hpp"
#include "conceptrodon/typelivore/left_interview.hpp"
#include "conceptrodon/typelivore/look_for.hpp"
#include "conceptrodon/typelivore/reconformed_left_interview.hpp"
#include "conceptrodon/typelivore/right_interview.hpp"
#include "conceptrodon/typelivore/sensible_left_interview.hpp"
#include "conceptrodon/typelivore/sensible_right_interview.hpp"
#include "conceptrodon/typelivore/set_contains.hpp"

#include "conceptrodon/descend/typelivore/amid.hpp"
#include "conceptrodon/descend/typelivore/amidst.hpp"
#include "conceptrodon/descend/typelivore/are_distinct.hpp"
#include "conceptrodon/descend/typelivore/are_overlapping.hpp"
#include "conceptrodon/descend/typelivore/conjure_set.hpp"
#include "conceptrodon/descend/typelivore/dismiss.hpp"
#include "conceptrodon/descend/typelivore/diversity.hpp"
#include "conceptrodon/descend/typelivore/duplicate.hpp"
#include "conceptrodon/descend/typelivore/erase.hpp"
#include "conceptrodon/descend/typelivore/flip.hpp"
#include "conceptrodon/descend/typelivore/front.hpp"
#include "conceptrodon/descend/typelivore/gauge.hpp"
#include "conceptrodon/descend/typelivore/grade.hpp"
#include "conceptrodon/descend/typelivore/has.hpp"
#include "conceptrodon/descend/typelivore/inject.hpp"
#include "conceptrodon/descend/typelivore/plume.hpp"
#include "conceptrodon/descend/typelivore/pop.hpp"
#include "conceptrodon/descend/typelivore/preen.hpp"
#include "conceptrodon/descend/typelivore/refurbish.hpp"
#include "conceptrodon/descend/typelivore/reiterate.hpp"
#include "conceptrodon/descend/typelivore/renovate.hpp"
#include "conceptrodon/descend/typelivore/rotate.hpp"
#include "conceptrodon/descend/typelivore/slice.hpp"
#include "conceptrodon/descend/typelivore/trim.hpp"
#include "conceptrodon/descend/typelivore/upend.hpp"


#include "conceptrodon/descend/descend/typelivore/are_unique.hpp"
#include "conceptrodon/descend/descend/typelivore/make_set.hpp"