// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

/******************************************************************************************************/
#ifdef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#error "CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY has already been defined"
#endif

#ifdef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#error "CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE has already been defined"
#endif

#ifdef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#error "CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE has already been defined"
#endif

#ifdef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#error "CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX has already been defined"
#endif

#ifdef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
#error "CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX has already been defined"
#endif
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_ROAD_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_ROAD_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_ROAD_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX    \
    typename
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    :: CONCEPTRODON_NUCLEOLUS_TYPE_RESULT

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/





/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_RAIL_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_RAIL_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_RAIL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    :: CONCEPTRODON_NUCLEOLUS_VALUE_RESULT

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_FLOW_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_FLOW_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_FLOW_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_MOLD_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_SAIL_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_SAIL_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_SAIL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_PAGE_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_SNOW_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_SNOW_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_SNOW_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_ROAD_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_HAIL_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_HAIL_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_HAIL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_RAIL_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_COOL_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_COOL_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_COOL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_FLOW_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_CALM_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_CALM_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_CALM_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_SAIL_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_GRIT_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_GRIT_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_GRIT_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_SNOW_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_WILL_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_WILL_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_WILL_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_HAIL_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_GLOW_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_GLOW_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_GLOW_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_COOL_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/




/******************************************************************************************************/
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY    \
    CONCEPTRODON_NUCLEOLUS_DAWN_PARAMETER_CATEGORY
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE    \
    CONCEPTRODON_NUCLEOLUS_DAWN_PROTO_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE   \
    CONCEPTRODON_NUCLEOLUS_DAWN_SYNOPSIS_TEMPLATE
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#define CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX    \
    ::template CONCEPTRODON_NUCLEOLUS_CALM_SYNOPSIS_TEMPLATE

#include "conceptrodon/metafunctions/microbiota/pagelis/classic_trip/ascend/classic_trip.hpp"

#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PARAMETER_CATEGORY
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_PROTO_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_SYNOPSIS_TEMPLATE
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_PREFIX
#undef CONCEPTRODON_PAGELIS_CLASSIC_TRIP_COMPOSITION_MEMBER_ACCESSOR_SUFFIX
/******************************************************************************************************/









